from sympy.combinatorics import Permutation


class SymmetricGroupGeneratorsConstructor(object):
    # Every Symmetric Group can be generated by two elements of order 2 and 3.
    # This class calculates those two elements for a given degree.
    #
    # I. M. S. Dey and J. Wiegold, "Generators for alternating and symmetric groups,"
    # J. Australian Math. Soc. 12 (1971), 63-68.

    def __init__(self, degree):
        self.degree = degree

