from sympy.combinatorics import Permutation


class SymmetricGroupGeneratorsConstructor(object):
    # Every Symmetric Group can be generated by two elements of order 2 and 3.
    # This class calculates those two elements for a given degree.
    #
    # I. M. S. Dey and J. Wiegold, "Generators for alternating and symmetric groups,"
    # J. Australian Math. Soc. 12 (1971), 63-68.

    def __init__(self, degree):
        self.degree = degree

    # Generates the permutation (1,2,3)(4,5,6)...(n-2,n-1,n)
    # i.e. the Permutation(0,1,2)(3,4,5)...(n-3,n-2,n-1) for python
    # for a given 'n' which is a multiple of 3
    def get_an(self, n):
        # Validate 'n'
        if n > self.degree:
            raise RuntimeError('Error in calculating An, n needs to be smaller than the degree.')
        if n <= 0 or n % 3 != 0:
            raise RuntimeError('Error in calculating An, n needs to be positive and a multiple of 3.')
        # Generate the permutation
        an = Permutation(self.degree-1)
        for i in range(0, n, 3):
            an = an*Permutation(i, i+1, i+2)
        return an

    # Generate the permutation (6,9)(7,10)(8,11)(12,15)(13,16)...(6k,6k+3)(6k+1,6k+4)(6k+2,6k+5)
    # i.e. the Permutation(5,8)(6,9)(7,10)(11,14)(12,15)...(6k-1,6k+2)(6k,6k+3)(6k+1,6k+4) in python
    # for a given 'k' which is greater or equal to 1
    def get_ck(self, k):
        # Validate 'k'
        if k > self.degree:
            raise RuntimeError('Error in calculating Ck, k needs to be smaller than the degree.')
        if k < 1:
            raise RuntimeError('Error in calculating Ck, k needs to be greater or equal to 1.')
        # Generate the permutation
        ck = Permutation(self.degree-1)
        for i in range(1, k+1):
            ck = ck*Permutation(6*i-1, 6*i+2)(6*i, 6*i+3)(6*i+1, 6*i+4)
        return ck

    def construct(self):
        n = self.degree
        # For n less than 19 we get the generators manually.
        if n < 19:
            if n < 7 or n == 8:
                # TODO: Add the cases for degree 1, 2, 3, 4, 5, 6 or 8 which are either trivial or not Gamma-groups
                raise RuntimeError('For Symmetric groups of degree 1, 2, 3, 4, 5, 6 or 8 is to be developed')
            elif n == 7:
                # a = a6, y = (1, 4)(2, 7)(3, 5)
                return self.get_an(6), Permutation(0, 3)(1, 6)(2, 4)
            elif n == 9:
                # a = a9, y = (1, 4)(2, 8)(5, 9)
                return self.get_an(9), Permutation(0, 3)(1, 7)(4, 8)
            elif n == 10:
                # a = a9, y = (1, 4)(2, 10)(3, 7)(5, 9)(6, 8)
                return self.get_an(9), Permutation(0, 3)(1, 9)(2, 6)(4, 8)(5, 7)
            elif n == 11:
                # a = a9, y = (1, 4)(2, 7)(5, 8)(6, 11)(3, 10)
                return self.get_an(9), Permutation(0, 3)(1, 6)(4, 7)(5, 10)(2, 9)
            elif n == 12:
                # a = a12, y = (1, 4)(2, 10)(3, 11)(6, 9)(7, 8)
                return self.get_an(12), Permutation(0, 3)(1, 9)(2, 10)(5, 8)(6, 7)
            elif n == 13:
                # a = a12, y = (1, 4)(2, 13)(6, 9)(7, 10)(8, 11)
                return self.get_an(12), Permutation(0, 3)(1, 12)(5, 8)(6, 9)(7, 10)
            elif n == 14:
                # a = a12, y = (1, 4)(2, 13)(3, 14)(5, 8)(6, 9)(7, 10)(11, 12)
                return self.get_an(12), Permutation(0, 3)(1, 12)(2, 13)(4, 7)(5, 8)(6, 9)(10, 11)
            elif n == 15:
                # a = a15, y = (1, 4)(3, 14)(6, 9)(7, 10)(12, 15)(5, 13)(2, 8)
                return self.get_an(15), Permutation(0, 3)(2, 13)(5, 8)(6, 9)(11, 14)(4, 12)(1, 7)
            elif n == 16:
                # a = a15, y = (1, 4)(2, 16)(6, 9)(7, 10)(8, 11)(3, 13)(5, 15)
                return self.get_an(15), Permutation(0, 3)(1, 15)(5, 8)(6, 9)(7, 10)(2, 12)(4, 14)
            elif n == 17:
                # a = a15, y = (1, 4)(2, 16)(3, 17)(12, 15)(6, 9)(7, 10)(8, 11)
                return self.get_an(15), Permutation(0, 3)(1, 15)(2, 16)(11, 14)(5, 8)(6, 9)(7, 10)
            elif n == 18:
                # a = a18, y = (1, 8)(2, 16)(3, 4)(5, 7)(6, 10)(12, 13)(9, 14)
                return self.get_an(18), Permutation(0, 7)(1, 15)(2, 3)(4, 6)(5, 9)(11, 12)(8, 13)
        # For n greater or equal to 19, we need to get the a, b1 and b2 elements
        # which will then be the components of the Symmetric Group generators.
        else:
            m = n // 6
            k = n % 6
            if k == 0:
                a = self.get_an(n-3)
                # b1 = (1,4)(2,n-2)(3,n-1)(n-6,n-3)(n-5,n)c_m-2
                b1 = Permutation(0, 3)(1, n-3)(2, n-2)(n-7, n-4)(n-6, n-1)*self.get_ck(m-2)
                # b2 = b1(n-11,n-8)
                b2 = b1*Permutation(n-12, n-9)
            elif k == 1:
                a = self.get_an(n-1)
                # b1 = (1,4)(2,n)(3,n-1)(n-6,n-3)(n-5,n-2)c_m-2
                b1 = Permutation(0, 3)(1, n-1)(2, n-2)(n-7, n-4)(n-6, n-3)*self.get_ck(m-2)
                # b2 = b1(n-12,n-9)
                b2 = b1*Permutation(n-13, n-10)
            elif k == 2:
                a = self.get_an(n-2)
                # b1 = (1,4)(2,n-1)(3,n)(n-8,n-5)(n-6,n-3)c_m-2
                b1 = Permutation(0, 3)(1, n-2)(2, n-1)(n-9, n-6)(n-7, n-4)*self.get_ck(m-2)
                # b2 = b1(n-7,n-4)
                b2 = b1*Permutation(n-8, n-5)
            elif k == 3:
                a = self.get_an(n-3)
                # b1 = (1,4)(2,n-2)(3,n-1)(n-3,n)c_m-1
                b1 = Permutation(0, 3)(1, n-3)(2, n-2)(n-4, n-1)*self.get_ck(m-1)
                # b2 = b1(n-8,n-5)
                b2 = b1*Permutation(n-9, n-6)
            elif k == 4:
                a = self.get_an(n-1)
                # b1 = (1,4)(2,n)(3,n-3)(n-10,n-7)(n-8,n-5)c_m-2
                b1 = Permutation(0, 3)(1, n-1)(2, n-4)(n-11, n-8)(n-9, n-6)*self.get_ck(m-2)
                # b2 = b1(n-9,n-6)
                b2 = b1*Permutation(n-10, n-7)
            else:  # k == 5
                a = self.get_an(n-2)
                # b1 = (1,4)(2,n-1)(3,n)(n-5,n-2)c_m-1
                b1 = Permutation(0, 3)(1, n-2)(2, n-1)(n-6, n-3)*self.get_ck(m-1)
                # b2 = b1(n-10,n-7)
                b2 = b1*Permutation(n-11, n-8)
            # Get the generators
            if m % 2 == 1:
                return a, b2
            else:  # m % 2 == 0
                return a, b1
